defaults:
  - launcher: local
  - solver: cem_physics
  - _self_

cache_dir: /oscar/data/jpober/cduong5/swm_cache
image_shape: [480, 480]

world:
  env_name: swm/PFRocketLanding-v0
  num_envs: ${eval.num_eval}
  max_episode_steps: ???
  history_size: 3
  frame_skip: 1
  render_mode: rgb_array

dataset:
  stats: ${eval.dataset_name}
  keys_to_cache:
    - action

seed: 42
policy: physics
warm_start_expert: true

plan_config:
  horizon: 40
  receding_horizon: 1
  action_block: 1

eval:
  num_eval: 4
  goal_offset_steps: 150
  eval_budget: 250
  img_size: 224
  dataset_name: rocket_expert
  callables: []

output:
  filename: rocket_physics_only_results.txt
