"""Aggregate RocketJEPA CLF-MPC tuning results into paper tables."""
from __future__ import annotations

import argparse
import csv
import json
import re
from pathlib import Path

import numpy as np


def parse_float_tag(text: str) -> float:
    return float(text.replace("p", ".").replace("m", "-"))


def load_rows(results_dir: Path) -> list[dict]:
    rows = []
    for path in sorted(results_dir.glob("*.json")):
        match = re.search(r"__lambda([^_]+)_eta([^_]+)__seed(\d+)\.json$", path.name)
        data = json.loads(path.read_text())
        lam = parse_float_tag(match.group(1)) if match else float(data.get("lambda_V", 0.0))
        eta = parse_float_tag(match.group(2)) if match else float(data.get("eta", 0.0))
        seed = int(match.group(3)) if match else None
        for level, metrics in data["by_level"].items():
            episode = metrics["episodes"][0]
            rows.append({
                "seed": seed,
                "level": level,
                "lambda_V": lam,
                "eta": eta,
                "success": float(metrics["success_rate"]),
                "violation_rate": float(metrics["violation_rate"]),
                "mean_descent_rate": float(metrics["mean_descent_rate"]),
                "return": float(metrics["mean_return"]),
                "steps": float(metrics["mean_steps"]),
                "final_V": float(episode["final_V"]),
                "max_V": float(episode["max_V"]),
            })
    return rows


def summarize(rows: list[dict]) -> list[dict]:
    out = []
    levels = sorted({r["level"] for r in rows})
    lambdas = sorted({r["lambda_V"] for r in rows})
    for level in levels:
        baseline = {r["seed"]: r for r in rows if r["level"] == level and r["lambda_V"] == 0.0}
        for lam in lambdas:
            subset = [r for r in rows if r["level"] == level and r["lambda_V"] == lam]
            if not subset:
                continue
            item = {
                "level": level,
                "lambda_V": lam,
                "n": len(subset),
                "success": float(np.mean([r["success"] for r in subset])),
                "violation_rate": float(np.mean([r["violation_rate"] for r in subset])),
                "mean_descent_rate": float(np.mean([r["mean_descent_rate"] for r in subset])),
                "return": float(np.mean([r["return"] for r in subset])),
                "steps": float(np.mean([r["steps"] for r in subset])),
                "final_V": float(np.mean([r["final_V"] for r in subset])),
                "max_V": float(np.mean([r["max_V"] for r in subset])),
                "delta_violation": "",
                "delta_return": "",
                "delta_final_V": "",
                "wins_violation": "",
                "wins_return": "",
            }
            if lam != 0.0:
                pairs = [(r, baseline[r["seed"]]) for r in subset if r["seed"] in baseline]
                dviol = np.array([r["violation_rate"] - b["violation_rate"] for r, b in pairs])
                dret = np.array([r["return"] - b["return"] for r, b in pairs])
                dfv = np.array([r["final_V"] - b["final_V"] for r, b in pairs])
                item.update({
                    "delta_violation": float(np.mean(dviol)),
                    "delta_return": float(np.mean(dret)),
                    "delta_final_V": float(np.mean(dfv)),
                    "wins_violation": f"{int(np.sum(dviol < 0))}/{len(pairs)}",
                    "wins_return": f"{int(np.sum(dret > 0))}/{len(pairs)}",
                })
            out.append(item)
    return out


def fmt(value, digits=3, scale=1.0):
    if value == "":
        return "--"
    value = float(value) * scale
    if abs(value) >= 1000:
        return f"{value:.1f}"
    return f"{value:.{digits}f}"


def write_csv(summary: list[dict], path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=list(summary[0]))
        writer.writeheader()
        writer.writerows(summary)


def write_tex(summary: list[dict], path: Path) -> None:
    lines = [
        "% Auto-generated by scripts/aggregate_rocket_clf.py",
        r"\begin{tabular}{llrrrrrr}",
        r"\toprule",
        r"Level & Controller & Success & Viol. & $\bar\delta$ & Return & $\Delta$ Viol. & Win$_V$ \\",
        r"\midrule",
    ]
    for row in summary:
        if row["lambda_V"] == 0.0:
            controller = "MPC"
        else:
            controller = rf"CLF $\lambda_V={row['lambda_V']:.0f}$"
        lines.append(
            f"{row['level']} & {controller} & "
            f"{fmt(row['success'], 0, 100)} & "
            f"{fmt(row['violation_rate'], 1, 100)} & "
            f"{fmt(row['mean_descent_rate'], 4)} & "
            f"{fmt(row['return'], 1)} & "
            f"{fmt(row['delta_violation'], 1, 100)} & "
            f"{row['wins_violation'] or '--'} \\\\"
        )
    lines.extend([r"\bottomrule", r"\end{tabular}", ""])
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines))


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--results-dir", type=Path,
                        default=Path("/users/aiyer40/scratch/results_lejepa_v4/clf_tune_physnorm"))
    parser.add_argument("--out-dir", type=Path,
                        default=Path("outputs/rocket_jepa/clf_tune"))
    args = parser.parse_args()

    rows = load_rows(args.results_dir)
    summary = summarize(rows)
    write_csv(summary, args.out_dir / "clf_tune_summary.csv")
    write_tex(summary, args.out_dir / "clf_tune_table.tex")
    print(f"Loaded {len(rows)} level rows from {args.results_dir}")
    print(f"Wrote {args.out_dir / 'clf_tune_summary.csv'}")
    print(f"Wrote {args.out_dir / 'clf_tune_table.tex'}")


if __name__ == "__main__":
    main()
