"""Aggregate RocketJEPA fallback evaluation JSONs."""
from __future__ import annotations

import argparse
import csv
import json
import re
from pathlib import Path

import numpy as np


def load_rows(results_dir: Path) -> list[dict]:
    rows: list[dict] = []
    seed_pat = re.compile(r"__seed(\d+)\.json$")
    for path in sorted(results_dir.glob("*.json")):
        data = json.loads(path.read_text())
        match = seed_pat.search(path.name)
        file_seed = int(match.group(1)) if match else None
        for level, metrics in data.get("by_level", {}).items():
            for ep in metrics.get("episodes", []):
                rows.append({
                    "path": str(path),
                    "seed": int(ep.get("seed", file_seed if file_seed is not None else -1)),
                    "level": level,
                    "success": float(bool(ep.get("success", False))),
                    "violation_rate": float(ep["violation_rate"]),
                    "mean_descent": float(ep["mean_descent"]),
                    "return": float(ep["return"]),
                    "steps": float(ep["T"]),
                    "final_V": float(ep.get("final_V", np.nan)),
                    "max_V": float(ep.get("max_V", np.nan)),
                    "fallback_triggered": float(bool(ep.get("fallback_triggered", False))),
                    "switchover_step": ep.get("switchover_step"),
                    "alarm_threshold": float(data.get("alarm_threshold", np.nan)),
                    "alarm_k": int(data.get("alarm_k", -1)),
                    "lambda_V": float(data.get("lambda_V", 0.0)),
                })
    return rows


def summarize(rows: list[dict]) -> list[dict]:
    out = []
    for level in sorted({r["level"] for r in rows}):
        subset = [r for r in rows if r["level"] == level]
        switched = [r["switchover_step"] for r in subset if r["switchover_step"] is not None]
        out.append({
            "level": level,
            "n": len(subset),
            "alarm_threshold": float(np.nanmean([r["alarm_threshold"] for r in subset])),
            "alarm_k": int(round(np.mean([r["alarm_k"] for r in subset]))),
            "success_rate": float(np.mean([r["success"] for r in subset])),
            "violation_rate": float(np.mean([r["violation_rate"] for r in subset])),
            "mean_descent": float(np.mean([r["mean_descent"] for r in subset])),
            "return": float(np.mean([r["return"] for r in subset])),
            "final_V": float(np.nanmean([r["final_V"] for r in subset])),
            "max_V": float(np.nanmean([r["max_V"] for r in subset])),
            "fallback_trigger_rate": float(np.mean([r["fallback_triggered"] for r in subset])),
            "mean_switchover_step": float(np.mean(switched)) if switched else float("nan"),
        })
    return out


def write_csv(rows: list[dict], path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if not rows:
        path.write_text("")
        return
    with path.open("w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=list(rows[0]))
        writer.writeheader()
        writer.writerows(rows)


def write_tex(summary: list[dict], path: Path) -> None:
    lines = [
        "% Auto-generated by scripts/analyze_rocket_fallback.py",
        r"\begin{tabular}{lrrrrrr}",
        r"\toprule",
        r"Level & Success & Viol. & Return & Trigger & Switch step & $n$ \\",
        r"\midrule",
    ]
    for r in summary:
        lines.append(
            f"{r['level']} & {100*r['success_rate']:.1f} & "
            f"{100*r['violation_rate']:.1f} & {r['return']:.1f} & "
            f"{100*r['fallback_trigger_rate']:.1f} & "
            f"{r['mean_switchover_step']:.1f} & {int(r['n'])} \\\\"
        )
    lines.extend([r"\bottomrule", r"\end{tabular}", ""])
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines))


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--results-dir", type=Path, required=True)
    parser.add_argument("--out-dir", type=Path, default=Path("outputs/rocket_jepa/fallback"))
    args = parser.parse_args()

    rows = load_rows(args.results_dir)
    summary = summarize(rows)
    args.out_dir.mkdir(parents=True, exist_ok=True)
    write_csv(rows, args.out_dir / "fallback_episodes.csv")
    write_csv(summary, args.out_dir / "fallback_summary.csv")
    write_tex(summary, args.out_dir / "fallback_table.tex")
    (args.out_dir / "fallback_summary.json").write_text(json.dumps(summary, indent=2))
    print(f"Loaded {len(rows)} fallback episodes from {args.results_dir}")
    print(f"Wrote {args.out_dir / 'fallback_summary.json'}")


if __name__ == "__main__":
    main()
